In [18]:
import torch
import numpy as np

In [27]:
device = "cuda" if torch.cuda.is_available() else "cpu"

test_tensor = torch.tensor([[1,2,3],[4,5,6]],
                           dtype = torch.float32,
                           device = device,
                          requires_grad = True)
print(test_tensor)
print(test_tensor.shape)
print(test_tensor.dtype)
print(test_tensor.device)
print(test_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)
torch.Size([2, 3])
torch.float32
cuda:0
True


In [12]:
print(torch.rand((3,3)))
print(torch.zeros((3,3)))
print(torch.ones((3,3)))
print(torch.eye(3,3))
print(torch.arange(1,5,1))
print(torch.linspace(0.1,1,10))

tensor([[0.1229, 0.2885, 0.1405],
        [0.4673, 0.3631, 0.2595],
        [0.7888, 0.6878, 0.1074]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([1, 2, 3, 4])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [16]:
#tensor.<dtype>() coverts tensor types

bit_tensor = torch.tensor([[0,1,0],[1,1,0],[1,0,0]])
bool_tensor = bit_tensor.bool()
print(bool_tensor)

tensor([[False,  True, False],
        [ True,  True, False],
        [ True, False, False]])


In [19]:
arr = np.zeros((3,3))
np_tensor = torch.from_numpy(arr)
np_arr = np_tensor.numpy()
print(np_tensor)
print(np_arr)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [45]:
x = torch.arange(1,4)
y = torch.arange(9,6,-1)

#Addition
z1 = x+y
print(z1)

#Subtraction
z2 = x-y
print(z2)

#Division
z3 = torch.true_divide(x,y)
print(z3)

#Exponentiaition
z4 = x ** 2
print(z4)

#Comparisons
z5 = x > 0
print(z5)

#Multiplication
torch.manual_seed(0)
a = torch.rand((3,5))
b = torch.rand((5,2))
c = a.mm(b)
print(a, a.shape)
print(b, b.shape)
print(c, c.shape)

#Matrix exponentiation
p = torch.rand(2,2)
print(p.matrix_power(2))

#Dot product
print(torch.dot(x,y))

tensor([10, 10, 10])
tensor([-8, -6, -4])
tensor([0.1111, 0.2500, 0.4286])
tensor([1, 4, 9])
tensor([True, True, True])
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074],
        [0.6341, 0.4901, 0.8964, 0.4556, 0.6323],
        [0.3489, 0.4017, 0.0223, 0.1689, 0.2939]]) torch.Size([3, 5])
tensor([[0.5185, 0.6977],
        [0.8000, 0.1610],
        [0.2823, 0.6816],
        [0.9152, 0.3971],
        [0.8742, 0.4194]]) torch.Size([5, 2])
tensor([[1.2864, 0.7116],
        [1.9436, 1.5784],
        [0.9200, 0.5136]]) torch.Size([3, 2])
tensor([[0.3402, 0.7033],
        [0.0267, 0.0688]])
tensor(46)
