In [42]:
import tensorflow as tf

In [56]:
# Initialization

x = tf.constant(10, shape=(1,1), dtype=tf.float32)
y = tf.constant([[1,2,3],[4,5,6]])

z = tf.ones((2,2)) # 2x2 matrix of ones
a = tf.zeros((3,3)) # 3x3 matrix of zeros
b = tf.eye(3) # 3x3 identity matrix

m = tf.random.normal((3,3), mean=0, stddev=1) # 3x3 matrix with random values from a standard normal distribution
n = tf.random.uniform((2,2), minval=0, maxval=1) # 2x2 matrix with random values from a uniform distribution

p = tf.range(9) # Vector from 0 to 8
q = tf.range(start=1, limit=10, delta=2) # [1,3,5,7,9]

y = tf.cast(y, dtype=tf.float16) # Typecast y to float16

In [74]:
# Operations

x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

# Addition
z = x + y
print(z)

# Subtraction
z = x - y
print(z)

# Element-wise division
z = x / y
print(z)

# Element-wise multiplication
z = x * y
print(z)

#Dot product
z = tf.tensordot(x, y, axes=1)
print(z)

# Element-wise exponentiation
z = x ** 3
print(z)

tf.random.set_seed(0)

# Matrix multiplication
x = tf.random.normal((3,4))
print(x)
y = tf.random.normal((4,2))
print(y)
z = tf.matmul(x, y)
print(z)
z = x @ y
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)
tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor([ 1  8 27], shape=(3,), dtype=int32)
tf.Tensor(
[[ 1.5110626   0.42292204 -0.41969493 -1.0360372 ]
 [-1.2368279   0.47027302 -0.01397489  1.1888583 ]
 [ 0.60253334  0.5997111  -0.7057119  -0.43297544]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[ 1.0668802   0.19454929]
 [-0.53082895  0.09190082]
 [-0.17753708 -0.91930884]
 [-2.0777557   2.0391903 ]], shape=(4, 2), dtype=float32)
tf.Tensor(
[[ 3.614767   -1.3940047 ]
 [-4.0368576   2.23975   ]
 [ 1.3493941  -0.06181574]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[ 3.614767   -1.3940047 ]
 [-4.0368576   2.23975   ]
 [ 1.3493941  -0.06181574]], shape=(3, 2), dtype=float32)


In [81]:
# Indexing
# Uses regular indexing and slicing

tf.random.set_seed(0)

x = tf.random.normal((1,5))
print(x)
indices = tf.constant([0,2])
z = tf.gather(x, indices, axis=1)
print(z)

y = tf.random.normal((3,2))
print(y)
print(y[0,:])
print(y[0:2,:])

tf.Tensor([[ 1.5110626   0.42292204 -0.41969493 -1.0360372  -1.2368279 ]], shape=(1, 5), dtype=float32)
tf.Tensor([[ 1.5110626  -0.41969493]], shape=(1, 2), dtype=float32)
tf.Tensor(
[[ 1.0668802   0.19454929]
 [-0.53082895  0.09190082]
 [-0.17753708 -0.91930884]], shape=(3, 2), dtype=float32)
tf.Tensor([1.0668802  0.19454929], shape=(2,), dtype=float32)
tf.Tensor(
[[ 1.0668802   0.19454929]
 [-0.53082895  0.09190082]], shape=(2, 2), dtype=float32)


In [87]:
# Reshaping

x = tf.range(15)
print(x)
x_rs = tf.reshape(x, (3,5))
print(x_rs)

y = tf.constant([[1,2,3],
               [4,5,6],
               [7,8,9]])
print(y)
y_T = tf.transpose(y, perm=[1,0]) # perm swaps rows and columns (axes 0 and 1 to 1 and 0)
print(y_T)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14], shape=(15,), dtype=int32)
tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]], shape=(3, 5), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[1 4 7]
 [2 5 8]
 [3 6 9]], shape=(3, 3), dtype=int32)
